repair UpperCaseCamelCase and add documentation for Word_History and …
Wifi-G9/backend pull request #20
Opened 2023-11-07 12:12 UTC by 916-Sicoe-Sergiu

…Word_of_the_Day tables and related procs

2023-11-07 18:35 UTC, bia1708 requested changes
I don't see any new models for the new tables. Have you added them? If not, could you please add them?
Please also add these tables in the `docs/Database/README.md`

2023-11-08 14:28 UTC, Sipos-Lucas-George commented
Please sign your commits @916-Sicoe-Sergiu, thank you in advance :kiss:

2023-11-08 20:20 UTC, bia1708 requested changes
Sign your commits and then you're good to go.

2023-11-10 16:52 UTC, bia1708 approved these changes

2023-11-10 16:52 UTC, merged